---
title: "Project 3 - SQL"
author: "Team 6"
output:
  prettydoc::html_pretty:
    theme: hpstr
    highlight: github
  pdf_document: default
editor_options: 
  chunk_output_type: console
---

# Team 6 - Project 3 SQL


Load libraries
```{r}
# Database Interaction
library(DBI)
# Pulling data from GH
library(RCurl)
#string manipulation
library(stringr)
```



```{r}
con <- dbConnect(RSQLite::SQLite(), dbname = ":memory:")

```

## Create Tables
```{r}
baseUrl <- "https://raw.githubusercontent.com/nolivercuny/data607-team-6-project-3/master/sql/"
tables <- c("company", "job_listing", "job_listing_skill")
for (table in tables) {
  fileUrl <- paste(baseUrl, table,".sql",sep = "")
  createTableStatement <- getURL(fileUrl)
  print(paste("Creating ", table, " table"))
  dbSendQuery(con, createTableStatement)
}
```

## Verify tables are created
```{r}
dbListTables(con)
dbListFields(con, "job_listing")
dbListFields(con, "company")
dbListFields(con, "job_listing_skill")
```

## Populate Tables

### Load Data From CSV
```{r}
urlfile<-"https://raw.githubusercontent.com/nolivercuny/data607-team-6-project-3/master/data/job_listings_final.csv" 
jobdat <- read_csv(url(urlfile))

#view short file summary and class
jobdat<-data_frame(jobdat)
```


### Populate Company Table
```{r}
companiesDf <- jobdat %>% select(company_name, company_size, industry) %>% distinct() 
companiesDf$company_name <- companiesDf$company_name %>% replace_na("unknown")
dbWriteTable(con,"company",companiesDf, append=TRUE)
```

### Populate Job Listing Table
```{r}
# Remove columns that are in the company table
jobListingDf <- jobdat %>% select(-c("company_size", "industry"))
# Fix the one company name that is NA
jobListingDf$company_name <- jobListingDf$company_name %>% replace_na("unknown")
# Read companies to get company ID for joining
companiesWithId <- dbReadTable(con,"company")
# Join job listing with company to populate id
# then drop company specific columns
# rename id column to company id
joined <- left_join(jobListingDf, companiesWithId, by="company_name") %>% 
  select(-c("company_size", "industry","company_name")) %>%
  rename(company_id = id)
#write dataframe to job_listing table
dbWriteTable(con, "job_listing", joined, append=TRUE)
```

### Populate Job Listing Skills Table
```{r}

```


## Close Connection
```{r}
dbDisconnect(con)
```

